import React, { useState } from 'react';
import { ShoppingCart, X, Check, Copy, Sparkles, ListTodo, Clipboard, Share2, Eye, EyeOff, ExternalLink, RefreshCw } from 'lucide-react';
import { Recipe, QuickCommPlatform } from '../types';
import { PLATFORM_INFO, MOCK_WEB_FALLBACKS } from '../data/mockData';
import { isNonVegIngredient } from '../utils/ingredientParser';

interface QuickCommModalProps {
  recipe: Recipe | null;
  onClose: () => void;
  selectedPlatform: QuickCommPlatform;
  setSelectedPlatform: (p: QuickCommPlatform) => void;
}

export const QuickCommModal: React.FC<QuickCommModalProps> = ({
  recipe,
  onClose,
  selectedPlatform,
  setSelectedPlatform,
}) => {
  const [useSubstitute, setUseSubstitute] = useState<Record<string, boolean>>({});
  const [boughtItems, setBoughtItems] = useState<Record<string, boolean>>({});
  const [copied, setCopied] = useState(false);
  const [showOnlyMissing, setShowOnlyMissing] = useState(false);

  if (!recipe) return null;

  const hasNonVegIngredients = recipe.ingredients.some((ing) => isNonVegIngredient(ing.name));

  // If FreshToHome is selected but recipe has no non-veg items, auto-fallback to Blinkit
  React.useEffect(() => {
    if (selectedPlatform === 'freshtohome' && !hasNonVegIngredients) {
      setSelectedPlatform('blinkit');
    }
  }, [recipe, selectedPlatform, hasNonVegIngredients, setSelectedPlatform]);

  const isFreshToHome = selectedPlatform === 'freshtohome';

  // For FreshToHome, we ONLY order/show non-veg items like chicken, meat, fish, eggs.
  const allIngredients = isFreshToHome
    ? recipe.ingredients.filter((ing) => isNonVegIngredient(ing.name))
    : recipe.ingredients;

  const missingIngredients = allIngredients.filter((ing) => ing.isMissing);
  
  // Exclude bought or pantry-item items from the list of ingredients to buy
  const activeMissingToBuy = missingIngredients.filter(ing => !boughtItems[ing.name] && !useSubstitute[ing.name]);
  
  const displayIngredients = showOnlyMissing ? missingIngredients : allIngredients;

  const getPackSize = (ingName: string): string => {
    const lower = ingName.toLowerCase();
    if (lower.includes('chicken') || lower.includes('meat') || lower.includes('mutton')) return '500g pre-cut pack';
    if (lower.includes('paneer') || lower.includes('cheese') || lower.includes('cream')) return '200g Fresh Pack';
    if (lower.includes('ghee') || lower.includes('oil')) return '500ml Bottle';
    if (lower.includes('cashew') || lower.includes('almond')) return '100g premium packet';
    if (lower.includes('onion') || lower.includes('tomato') || lower.includes('potato')) return '1 Kg Pack';
    if (lower.includes('powder') || lower.includes('masala')) return '100g spice box';
    return '1 Pack';
  };

  // Calculations
  const platformInfo = PLATFORM_INFO[selectedPlatform];

  const toggleBought = (name: string) => {
    setBoughtItems((prev) => ({
      ...prev,
      [name]: !prev[name],
    }));
  };

  // Generate clipboard text
  const handleCopyList = () => {
    const lines: string[] = [];
    lines.push(`🛒 QUICK-COMM CHECKLIST: ${recipe.title.toUpperCase()}`);
    lines.push(`👥 Portion Size: ${recipe.servings} People`);
    lines.push(`🚚 Delivery App: ${platformInfo.name}`);
    lines.push(`----------------------------------------`);
    
    activeMissingToBuy.forEach((ing) => {
      const qtyStr = ing.quantity ? `${ing.quantity} ${ing.unit || ''}` : '';
      const nameStr = ing.regionalName && ing.regionalName.toLowerCase() !== ing.name.toLowerCase()
        ? `${ing.name} (${ing.regionalName})`
        : ing.name;
      lines.push(`[ ] ${qtyStr ? qtyStr + ' ' : ''}${nameStr} -> Buy ${getPackSize(ing.name)}`);
    });

    lines.push(`----------------------------------------`);
    lines.push(`Generated by Annapurna AI Indian Recipe Finder`);
    
    navigator.clipboard.writeText(lines.join('\n'));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const redirectUrl = MOCK_WEB_FALLBACKS[selectedPlatform](activeMissingToBuy.map(i => i.name));

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-end sm:items-center justify-center p-0 sm:p-4 overflow-y-auto">
      <div className="bg-[#181311] border border-[#2a221f] rounded-t-3xl sm:rounded-3xl max-w-xl w-full p-5 sm:p-6 shadow-2xl relative text-[#f0e6df] overflow-y-auto max-h-[92vh] sm:max-h-[85vh] animate-fadeIn">
        
        {/* Top Accent line */}
        <div className="absolute top-0 left-0 right-0 h-1 bg-[#ff6224]" />

        {/* Prominent Close Button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 z-50 w-9 h-9 rounded-full bg-[#120f0e] hover:bg-[#241c19] text-[#f0e6df] flex items-center justify-center transition-all shadow-lg cursor-pointer hover:scale-105 border border-[#2a221f]"
          aria-label="Close modal"
        >
          <X className="w-5 h-5" />
        </button>
            {/* Modal Title Header */}
            <div className="flex items-center gap-3 mb-4 pr-12">
              <div className="w-10 h-10 rounded-xl bg-[#ff6224]/10 text-[#ff6224] border border-[#ff6224]/20 flex items-center justify-center shrink-0">
                <ShoppingCart className="w-5 h-5" />
              </div>
              <div>
                <span className="text-[11px] font-bold text-[#ff6224] uppercase tracking-wider block">
                  Quick-Commerce Cart Redirection
                </span>
                <h3 className="text-lg font-bold font-serif text-white line-clamp-1">
                  Shopping List for "{recipe.title}"
                </h3>
              </div>
            </div>

            {/* Quick platform selector tabs inside the modal */}
            <div className="mb-4 bg-[#241c19] p-2 rounded-2xl border border-[#352a25]">
              <span className="text-[10px] font-bold text-[#a09088] uppercase tracking-wider block px-1.5 mb-1.5">
                Select Quick-Comm Provider:
              </span>
              <div className="grid grid-cols-4 gap-1.5">
                {(['blinkit', 'zepto', 'instamart', 'freshtohome'] as QuickCommPlatform[]).map((p) => {
                  const info = PLATFORM_INFO[p];
                  const isActive = selectedPlatform === p;
                  const isFTH = p === 'freshtohome';
                  const isDisabledFTH = isFTH && !hasNonVegIngredients;

                  return (
                    <button
                      key={p}
                      disabled={isDisabledFTH}
                      onClick={() => setSelectedPlatform(p)}
                      className={`py-2 px-1 rounded-xl text-[10px] sm:text-xs font-bold transition-all text-center border cursor-pointer flex flex-col items-center justify-center min-h-[42px] ${
                        isActive
                          ? 'bg-[#ff6224] text-white border-transparent shadow-md font-extrabold'
                          : isDisabledFTH
                          ? 'bg-[#120f0e] text-[#a09088]/40 border-[#2a221f] opacity-40 cursor-not-allowed'
                          : 'bg-[#120f0e] text-[#a09088] border-[#2a221f] hover:bg-[#302521] hover:text-white'
                      }`}
                      title={isDisabledFTH ? 'No non-veg ingredients in this recipe' : info.name}
                    >
                      <span>{info.name}</span>
                      {isFTH && (
                        <span className="text-[8px] font-bold text-amber-400">Non-Veg Only</span>
                      )}
                    </button>
                  );
                })}
              </div>
            </div>

            {isFreshToHome && (
              <div className="mb-4 bg-amber-950/20 border border-amber-500/30 p-3 rounded-2xl flex items-start gap-2.5 text-xs text-[#f0e6df] shadow-2xs">
                <span className="text-amber-400 font-bold shrink-0">🍗 FreshToHome Filter:</span>
                <p className="text-[#a09088] leading-relaxed text-[11px]">
                  FreshToHome orders only <b>non-vegetarian items</b> (chicken, meat, fish, eggs). Vegetarian pantry items are automatically filtered out from this order.
                </p>
              </div>
            )}

            {/* Scale disclaimer */}
            <div className="mb-4 bg-[#241c19] border border-[#352a25] p-3 rounded-2xl flex items-center justify-between gap-3 text-xs text-[#f0e6df]">
              <p className="font-semibold text-xs">
                Portion size: <span className="text-[#ff6224] font-bold">{recipe.servings} People</span>
              </p>
              <button
                onClick={() => setShowOnlyMissing((prev) => !prev)}
                className="px-2.5 py-1.5 rounded-xl border border-[#2a221f] bg-[#120f0e] hover:bg-[#302521] font-bold text-[11px] text-[#f0e6df] flex items-center gap-1 transition-all cursor-pointer"
              >
                {showOnlyMissing ? (
                  <>
                    <Eye className="w-3.5 h-3.5 text-[#ff6224]" />
                    <span>Show All ({allIngredients.length})</span>
                  </>
                ) : (
                  <>
                    <EyeOff className="w-3.5 h-3.5 text-[#ff6224]" />
                    <span>Missing Only ({missingIngredients.length})</span>
                  </>
                )}
              </button>
            </div>

            {/* Ingredients Cart List */}
            <div className="space-y-2 mb-4 max-h-56 overflow-y-auto pr-1">
              {displayIngredients.length === 0 ? (
                <div className="p-6 text-center text-[#a09088] border border-dashed border-[#2a221f] rounded-2xl bg-[#120f0e]">
                  <Check className="w-8 h-8 text-emerald-400 mx-auto mb-2" />
                  <p className="font-bold text-sm text-white">All required items acquired!</p>
                </div>
              ) : (
                displayIngredients.map((ing, idx) => {
                  const isSubstituted = useSubstitute[ing.name];
                  const isChecked = boughtItems[ing.name];
                  const isNonVeg = isNonVegIngredient(ing.name);
                  const packSize = getPackSize(ing.name);

                  const displayName = ing.regionalName && ing.regionalName.toLowerCase() !== ing.name.toLowerCase()
                    ? `${ing.name} (${ing.regionalName})`
                    : ing.name;

                  return (
                    <div
                      key={`${ing.name}-${idx}`}
                      className={`p-3 rounded-xl border transition-all ${
                        isChecked
                          ? 'bg-[#120f0e] border-[#2a221f] opacity-50 line-through text-[#a09088]'
                          : isSubstituted
                          ? 'bg-amber-950/20 border-amber-500/30'
                          : ing.isMissing
                          ? 'bg-red-950/20 border-red-500/30 text-white'
                          : 'bg-[#241c19] border-[#352a25]'
                      }`}
                    >
                      <div className="flex items-center justify-between gap-3">
                        <div className="flex items-center gap-3 flex-1 min-w-0">
                          {/* Checkbox */}
                          <button
                            onClick={() => toggleBought(ing.name)}
                            className={`w-5 h-5 rounded-md border flex items-center justify-center transition-all cursor-pointer ${
                              isChecked
                                ? 'bg-[#ff6224] border-transparent text-white'
                                : 'bg-[#120f0e] border-[#2a221f] hover:border-[#ff6224] text-transparent'
                            }`}
                            title={isChecked ? 'To buy' : 'In stock'}
                          >
                            <Check className="w-3.5 h-3.5 stroke-[3]" />
                          </button>

                          {/* Food Type Dot */}
                          <span
                            className={`w-3.5 h-3.5 border rounded-xs bg-[#120f0e] flex items-center justify-center shrink-0 ${
                              isNonVeg ? 'border-red-500' : 'border-emerald-500'
                            }`}
                          >
                            <span className={`w-1.5 h-1.5 rounded-full ${isNonVeg ? 'bg-red-500' : 'bg-emerald-500'}`} />
                          </span>

                          {/* Details */}
                          <div className="min-w-0 flex-1">
                            <div className={`font-bold text-xs ${isChecked ? 'text-[#a09088]' : 'text-white'}`}>
                              {displayName}
                            </div>
                            <div className="text-[10px] text-[#a09088] font-medium">
                              Need: {ing.quantity ? `${ing.quantity} ${ing.unit || ''}` : 'To taste'} • Pack: {packSize}
                            </div>
                          </div>
                        </div>

                        {/* Status Tag or Substitute Button */}
                        <div className="text-right shrink-0">
                          {isSubstituted ? (
                            <span className="text-[9px] font-bold text-amber-400 uppercase bg-amber-950/50 border border-amber-500/40 px-1.5 py-0.5 rounded">Alt</span>
                          ) : isChecked ? (
                            <span className="text-[9px] font-bold text-[#a09088] uppercase bg-[#120f0e] border border-[#2a221f] px-1.5 py-0.5 rounded">Have</span>
                          ) : ing.isMissing ? (
                            <span className="text-[9px] font-bold text-red-400 uppercase bg-red-950/50 border border-red-500/40 px-1.5 py-0.5 rounded">Missing</span>
                          ) : (
                            <span className="text-[9px] font-bold text-emerald-400 uppercase bg-emerald-950/50 border border-emerald-500/40 px-1.5 py-0.5 rounded">Pantry</span>
                          )}

                          {ing.substituteOption && !isChecked && (
                            <button
                              onClick={() =>
                                setUseSubstitute((prev) => ({
                                  ...prev,
                                  [ing.name]: !prev[ing.name],
                                }))
                              }
                              className={`block mt-1 text-[9px] font-bold px-1.5 py-0.5 rounded border transition-all cursor-pointer ${
                                isSubstituted
                                  ? 'bg-[#ff6224] text-white border-transparent'
                                  : 'bg-[#120f0e] border-[#2a221f] text-[#a09088] hover:text-white'
                              }`}
                            >
                              {isSubstituted ? 'Alt Active' : 'Alt Option'}
                            </button>
                          )}
                        </div>
                      </div>

                      {isSubstituted && ing.substituteOption && !isChecked && (
                        <div className="mt-1.5 pt-1 border-t border-dashed border-amber-500/30 text-[10px] text-amber-300 font-medium flex items-center gap-1">
                          <Sparkles className="w-3 h-3 text-amber-400 shrink-0" />
                          <span>Using pantry substitute: <b>{ing.substituteOption}</b></span>
                        </div>
                      )}
                    </div>
                  );
                })
              )}
            </div>

            {/* Bottom Redirect Actions */}
            <div className="flex flex-col gap-2">
              <a
                href={redirectUrl}
                target="_blank"
                rel="noreferrer noopener"
                onClick={handleCopyList}
                className="w-full py-3.5 px-4 rounded-xl font-bold text-sm transition-all shadow-md flex items-center justify-center gap-2 bg-[#ff6224] hover:bg-[#e85418] text-white cursor-pointer"
              >
                <ExternalLink className="w-4 h-4" />
                <span>Redirect to {platformInfo.name} & Search Cart</span>
              </a>

              <div className="flex gap-2">
                <button
                  onClick={handleCopyList}
                  className="flex-1 py-2.5 px-3 rounded-xl border border-[#2a221f] bg-[#241c19] hover:bg-[#302521] font-bold text-xs text-[#f0e6df] flex items-center justify-center gap-1 cursor-pointer"
                >
                  <Clipboard className="w-3.5 h-3.5 text-[#ff6224]" />
                  <span>{copied ? 'Copied!' : 'Copy Checklist'}</span>
                </button>
                <button
                  onClick={onClose}
                  className="py-2.5 px-4 rounded-xl border border-[#2a221f] bg-[#120f0e] hover:bg-[#241c19] font-bold text-xs text-[#a09088] cursor-pointer"
                >
                  Cancel
                </button>
              </div>

              {/* Informative user disclaimer */}
              <p className="text-[9px] text-[#a09088] font-medium leading-relaxed text-center mt-2">
                Disclaimer: Annapurna AI redirect link opens {platformInfo.name} with missing ingredients pre-selected for instant quick-commerce ordering.
              </p>
            </div>

      </div>
    </div>
  );
};
